#!/usr/bin/env bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

export TARGET=$1
export TAG=$2

pushd $SCRIPT_DIR > /dev/null
    source venv/bin/activate

    echo "fab commands are now available. Examples:

Set a device into DUT mode:
    fab flashhost_dut

Set a device into Host mode:
    fab flashhost_host

Flash and provision an image:
    fab flashhost_flash_and_provision:<image>[,firstrun=False]

List all images:
    fab flashhost_list_images

--------------------------------------------

TARGET: $TARGET
TAG:    $TAG

Hit Ctrl-D to exit"

    bash

popd > /dev/null
